[tools]
"aqua:JanDeDobbeleer/oh-my-posh" = "28.2.0"
"aqua:ivaaaan/smug" = "0.3.12"
"github:Dark-Alex-17/managarr" = "latest"
"github:joshmedeski/sesh" = "2.24.2"
"pipx:pgcli" = { version = "latest", extras = "sshtunnel" }
atuin = "18.10.0"
bat = "0.26.1"
bat-extras = "2024.08.24"
bitwarden = "2025.12.0"
btop = "1.4.5"
chezmoi = "2.68.1"
cidrchk = "0.5"
doggo = "1.1.2"
duf = "0.9.1"
dust = "1.2.3"
eza = "0.23.4"
fastfetch = "2.56.0"
fd = "10.3.0"
fzf = "0.67.0"
github-cli = "2.83.2"
gping = "1.20.1"
gum = "0.17.0"
hadolint = "2.14.0"
lazydocker = "0.24.2"
lazygit = "0.57.0"
neovim = "0.12.1"
node = "22"
opencode = "1.3.0"
postgres = "18.3"
ripgrep = "15.1.0"
ripgrep-all = "0.10.10"
ripsecrets = "0.1.11"
rust = "1.94.1"
shellcheck = "0.11.0"
stern = "1.33.1"
television = "0.15.4"
terraform-docs = "0.20.0"
terraform-ls = "0.38.6"
terraform-validator = "3.1.3"
tflint = "0.60.0"
tlrc = "1.12.0"
tmux = "3.6a"
tree-sitter = "0.26.7"
usage = "2.14.0"
usql = "0.19.26"
uv = "0.10.11"
yazi = "26.1.4"
zoxide = "0.9.8"

[env]
IS_MONTBLU_DEVOPS = "yes"
