# ────────────────────────────────────────────────────────────
#  Hyprlock — minimal blur with ringed input
# ────────────────────────────────────────────────────────────

# Catppuccin Frappe
$base = rgba(303446ff)
$crust = rgba(232634ff)
$surface0 = rgba(414559ff)
$surface1 = rgba(51576dff)
$text = rgb(198, 208, 245)
$subtext1 = rgb(181, 191, 226)
$red = rgb(231, 130, 132)
$green = rgb(166, 209, 137)
$blue = rgb(140, 170, 238)
$lavender = rgb(186, 187, 241)
$mauve = rgb(202, 158, 230)

general {
    hide_cursor = true
}

background {
    monitor =
    color = $base
}

animations {
    enabled = false
}

input-field {
    monitor =
    size = 600, 100
    position = 0, 0
    halign = center
    valign = center

    inner_color = $base
    outer_color = $surface1 $surface0 90deg
    outline_thickness = 4

    font_family = CaskaydiaMono Nerd Font
    font_color = $text

    placeholder_text =   Enter Password 󰈷 
    check_color = $green $blue 120deg
    fail_color = $red $red 40deg

    rounding = 0
    fade_on_empty = false
    dots_spacing = 0.3
}

auth {
    fingerprint {
        enabled = true
    }
}
