general {
    lock_cmd         = pidof hyprlock || hyprlock
    before_sleep_cmd = ~/.scripts/hypr-pre-sleep.sh
    after_sleep_cmd  = ~/.scripts/hypr-post-wake.sh
}

listener {
    timeout  = 60                           # 1 min: dim brightness
    on-timeout = brightnessctl -s set 10
    on-resume  = brightnessctl -r
}

listener {
    timeout  = 120                          # 2 min: keyboard backlight off
    on-timeout = asusctl aura-power keyboard --sleep
    on-resume  = asusctl aura-power keyboard --awake
}

listener {
    timeout  = 150                          # 2.5 min: lock screen
    on-timeout = loginctl lock-session
}

listener {
    timeout  = 180                          # 3 min: blank OLEDs
    on-timeout = ~/.scripts/hypr-idle-dpms-off.sh
    on-resume  = ~/.scripts/hypr-idle-dpms-on.sh
}

listener {
    timeout  = 1800                         # 30 min: suspend
    on-timeout = systemctl suspend
}
