-- Generated by nwg-displays on 2026-06-24 at 10:33:05. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2560x1600@240.0",
    position = "3840x80",
    scale = 1.6
})
hl.monitor({
    output = "DP-1",
    mode = "3840x1080@120.0",
    position = "0x0",
    scale = 1.0
})
